<?php
/**
 * Created by PhpStorm.
 * User: lazaro
 * Date: 15/01/19
 * Time: 01:26 PM
 */

/**
 * @var \Veem\Payment\Block\Info $block
 * @see \Veem\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
    <dl class="payment-method">
        <dt class="v-logo">
            <img class="default"/>
        </dt>
    <dt id="v-payment-title" class="title"><?= /* @noEscape */ $title ?></dt>
<?php if ($specificInfo):?>
    <?php foreach ($specificInfo as $label => $value):
        if ($label == 'veem_email') {
            echo '<dt class="v-email-s">'. /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))). '</dt>';
        }
        if ($label == 'veem_fname') {
            echo '<dt class="v-info">'. /* @noEscape */ nl2br($block->escapeHtml(implode(" ", $block->getValueAsArray($value, true))));
        }
        if ($label == 'veem_lname') {
            echo /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))).'</dt>';
        }
        if ($label == 'veem_country') {
            $country = $block->getCountryName($value);
            echo '<dt class="v-info">'./* @noEscape */ nl2br($country).'</dt>';
        }
        if ($label == 'veem_phone') {
            echo '<dt class="v-info">'. /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray(ltrim($value, "tel:+1-"), true)))).'</dt><br />';
        }
        ?>
    <?php endforeach; ?>
<?php endif;?>
</dl>