<?php
/**
 * Created by PhpStorm.
 * User: lazaro
 * Date: 18/12/18
 * Time: 04:09 PM
 */
/** @var  \Veem\Payment\Block\Form $block */
$code = $block->escapeHtml($block->getMethodCode());

$countryOptions = $block->getCountryOptions();
?>
<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= /* @noEscape */ $code ?>"
          style="display:none"
>
    <div class="admin__field _required">
        <label class="label admin__field-label" for="<?= /* @noEscape */ $code ?>_email">
            <span><?= $block->escapeHtml(__('Email Address')) ?></span>
        </label>
        <div class="admin__field-control control">
            <input type="email" name="payment[email]"
                   class="required-entry input-text admin__control-text required-entry _required"/>
        </div>
    </div>

    <div class="admin__field _required">
        <label class="label admin__field-label" for="<?= /* @noEscape */ $code ?>_firstName">
            <span><?= $block->escapeHtml(__('First Name')) ?></span>
        </label>
        <div class="admin__field-control control">
            <input type="text" name="payment[fname]"
                   class="required-entry input-text admin__control-text required-entry _required"/>
        </div>
    </div>

    <div class="admin__field _required">
        <label class="label admin__field-label" for="<?= /* @noEscape */ $code ?>_lastName">
            <span><?= $block->escapeHtml(__('Last Name')) ?></span>
        </label>
        <div class="admin__field-control control">
            <input type="text" name="payment[lname]"
                   class="required-entry input-text admin__control-text required-entry _required"/>
        </div>
    </div>

    <div class="admin__field _required">
        <label class="label admin__field-label" for="<?= /* @noEscape */ $code ?>_countryCode">
            <span><?= $block->escapeHtml(__('Country')) ?></span>
        </label>
        <div class="admin__field-control control">
            <select name="payment[country]"
                   class="select admin__control-select required-entry _required">
                <?php foreach ($countryOptions as $countryOption) { ?>
                    <option value="<?= $countryOption['value'] ?>"><?= $countryOption['label'] ?></option>
                <?php } ?>
            </select>
        </div>
    </div>

    <div class="admin__field _required">
        <label class="label admin__field-label" for="<?= /* @noEscape */ $code ?>_phone">
            <span><?= $block->escapeHtml(__('Telephone')) ?></span>
        </label>
        <div class="admin__field-control control">
            <input type="tel" name="payment[phone]"
                   class="required-entry input-text admin__control-text required-entry _required"/>
        </div>
    </div>
</fieldset>
