<?php
/**
 * Created by PhpStorm
 * User: tania
 * Date: 01/18/19
 */
?>
<?php
/**
 * @var \Veem\Payment\Block\Info $block
 * @see \Veem\Payment\Block\Info
 */
$method = $block->getMethodTitle();
if ($method == 'veem'):
    $specificInfo = $block->getOrderPayment();
    if (isset($specificInfo)):?>
        <?php foreach($specificInfo as $label => $value):
            if ($label == 'claim_link' && $specificInfo['veem_payment_status'] === \Veem\Payment\Gateway\Helper\Response::VEEM_STATUS_SENT) { ?>
                <div class="page messages">
                    <div data-placeholder="messages"></div>
                    <div role="alert" class="messages">
                        <div class="message-warning warning message" data-ui-id="message-warning">
                            <span class="v-sent-message">We have approved your order and are requesting payment.
                                Please click button to approve payment through your Veem account.
                            </span>
                            <?= $block->getLinkButton($value); ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>